on:
  push:
    branches:
      - main

name: 🚀 Deploy Laravel app

jobs:
  deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check PHP version
        run: php -v

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo_mysql, exif, pcntl, bcmath, gd, zip

      - name: Install Dependencies
        run: composer install --no-script

      - name: Copy Env File
        run: cp .env.live .env

      - name: Generate Key
        run: php artisan key:generate

      # - name: Run Tests
      #   run: php artisan test

      - name: 📂 Deploy code
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.CICD_FTP_SERVER }}
          username: ${{ secrets.CICD_USER_NAME }}
          password: ${{ secrets.CICD_PASS }}
          server-dir: /public_html/
          timeout: 999999
